server:
  name: go-authentication
  port: 8082

project_id: go-firestore-rest-api
credentials: '
  {
    "type": "service_account",
    "project_id": "go-firestore-rest-api",
    "private_key_id": "6b1620dcbaa47bfc0ddda412cf8612519b41c875",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCckrKXCNNM8OQg\nQ3PUkX74ckRzVvD15I3GUow5hhb0aVW7rzA+ZvYFxRcpq9QZlJAWFc+filIorT7O\nDYW4xt0u+yzLCDa+tIejvL/ecQ7f2GEmiN4JUgMHHNP+zgMaC3rzbUuDUmjaEjjz\nrMqdjd8elg9ZY91rw5gkMOelG8ifYx/fd4H9gUwAejtIscqZ2KZRSY5lYsJlDRbI\nS7fCFMFZKlyTj576w3BI84YrwaifMF/Ogf87fz6Wf6DS16Aog7eKzhrlRGKd+yqL\n7wFoPK4nQdqEr0Cnr2mhUKTwSavQHB4kZlDwiZSwKY8AFo/WjNPekqUhNlPcJu3q\nCatbr2wHAgMBAAECggEAE42SYKAz2xZI4ZVANYScqaQuKNqWVEQ1nFXEuI5RTDaM\nrq1DG206PiA4iKCyZ9C7abam62ftDggMoX440TQsfRMrAIlHD5Z19fG6uFRqz3OI\ni7UTSBtbe3Doh0KXn+ddHwyVczyVvDNYX2iYaQfwRt6QjiZANEFZ553KipOnVe1r\nWHa99twnxt+XWHoJUHO1RyI6FrNOw+K+Coj1reQnS7/1QXaixe0/p0Wwo6qdUsEy\n2ftm8N7UsLCa5kWT3x8/XJfi50VvgleHSfGsW+Vj/tojljv0enXbwFtFqRs44evv\nwhDI4qOclUy3hNMbkc8d54S2zvWbRuv+BsklJU8gIQKBgQDTK2zyi+uXYR+DJYL6\nWqbrQoVkzmU7Sq2BQMq5/m/BncRPkAEdaQ1DyLpM6fwNp/FntYcu4FGI76bvJsji\nnAwRalAqOzu4d8YnUNbsaHFB+wELmA/a/oymyNL7pOnfjhq+QQlF0TJsV/ZZKFWG\nz7aKSGvKVxhvu6oAHK6r3GqkEQKBgQC90BM+GUeXes8E6l4lQlJNBatHLqlci/a8\n/r2NOd//CVaxSjWiYmf/zANNC6lG7X3KTI/PVhZQ5TVFzd2wpnJA9tymDDrP67QH\nSEjg7sQDQ9gM+yvhni1xCyxIU8gVVQdhOP/ih47RPAoQGmFRm48YJ+TTBYjOhGq3\nL2EcLSxGlwKBgQDD4JkrlxyOi7nGVepbvfDtcwP3UPhX+lpc9bPWuSwDBgwN3T8b\nf9GdGbmuFLEIHctwbtMZaVxYUCyh03Etup/7G4mG0vD/mKKG35atLeg40tLSZVf3\nxHzFTK1gXUXPZ6po5jzqtTU3iJRreV10MoJZXPoXc5ioNARqHDDuHAQTcQKBgFQB\nnBKWw52iJ69IPsSEtsIJ6UUGvMQN2fTJVYEEhUNtkaXDbztgDCEk3K0jpRaUE2EO\nQ3OC6TuCRfKP6za8Y8Kmvv7qWLke2z2B22dZpPzA8QTFwSUIiZoHVODp25q9WBfK\nT02lqyqlRNrdogapL0qElXxjbang5w4N9Q+wWnEfAoGAFnDhTzlb3nsYAvVe8OMP\nsm6x4u0OZRkJ+Z+m6CA19RgV0snOXwH8To9HzXFgnLA7l0EDgqEAgas2PE16nJtb\nEWABTOcXMdmlxLPinp8ejpb6eIaI+uIBF6A8my/sIB+XPZvKWV+FTnySv5KDJ3RL\nOI5ZGIDQDdE+QOqwu4Qjmzk=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-srrcy@go-firestore-rest-api.iam.gserviceaccount.com",
    "client_id": "101673912751802204503",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-srrcy%40go-firestore-rest-api.iam.gserviceaccount.com"
  }'
mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: user
location:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: location
sql:
  driver: postgres
  data_source_name: host=localhost port=5432 user=postgres dbname=masterdata sslmode=disable password=abcd1234
redis:
  url: redis://localhost:6379

mail:
  from:
    name: Supporter
    address: testsmtp318@gmail.com
  provider: smtp
  api_key:
  smtp:
    host: smtp.gmail.com
    port: 465
    username: testsmtp318@gmail.com
    password: vaseaqiscbgedkga
    ssl: true

max_password_failed: 5
locked_minutes: 60
max_password_age: 90
password_encryption_key:

token:
  secret: secretauthentication
  expires: 86400000
payload:
  ip: ip
  user_id: userId
  username: username
  contact: email
  user_type: roleId

callback_url:
  microsoft: http://localhost:3001/auth/connect/oauth2
  amazon: http://localhost:3001/index.html?redirect=oauth2
  twitter: http://localhost:3001/index.html?redirect=oauth2

status:
  deactivated: D
  suspended: S
  disable: E
auth:
  expires: 3600
  template:
    subject: "%s Verification Code"
    body: "%s Use this code for verification"
  schema:
    id: userId
    username: username
    success_time: successTime
    fail_time: failTime
    fail_count: failCount
    locked_until_time: lockedUntilTime
    roles: roles
    password: password
    password_changed_time: passwordModifiedTime
    status: status
    contact: email
    display_name: displayName
    max_password_age: maxPasswordAge
    user_type: userType
    access_date_from: accessDateFrom
    access_date_to: accessDateTo
    is_two_factor: isTwoFactor

auth_sql:
  query: select user_id as userid, username, email as contact, display_name as displayname, status from user where username = ?
  pass: update users set last_login = ? where user_id = ?
  disable: D

sign_up:
  expires: 3600
  user_verified:
    secure: false
    domain: localhost
    port: 3002
    action: /signup/verify
  user_status:
    registered: R
    verifying: V
    activated: A
  schema:
    user_id: userId
    username: username
    contact: email
    signed_up_time: signedUpTime
    language: language
    max_password_age: maxPasswordAge
    date_of_birth: dateOfBirth
    given_name: givenName
    middle_name: middleName
    family_name: familyName
    gender: gender
    created_time: createdTime
    created_by: createdBy
    updated_time: updatedTime
    updated_by: updatedBy
    version: version
  template:
    subject: Verify your email address
    body: |
      Please click this link to confirm to activate your account:<br><a href="%s">Confirm Now</a><br><br>
      If the above button doesn't work for you, please click on the below link or copy paste it on to your browser<br>
      <a href="%s">%s</a><br><br>
      Your link will expire after "%s" minutes.
      <br><br><br>
      Hẫy nhấn đường link ở đây để kích hoạt cài khoản của bạn: <br><a href="%s">Xác nhận</a><br><br>
      Nếu đường link đó không hoạt động, hãy sao chép đường link đó và dán vào trình duyệt web của bạn<br>
      <a href="%s">%s</a><br><br>
      Đường link này sẽ hết hạn sau "%s" phút.

oauth2:
  services: google
  schema:
    user_id: userId
    username: username
    email: email
    status: status
    oauth2_email: Email
    account: Account
    active: Active
    picture: picture
    locale: language
    gender: gender
    date_of_birth: dateOfBirth
    given_name: givenName
    middle_name: middleName
    family_name: familyName
    display_name: displayName
    created_time: createdTime
    created_by: createdBy
    updated_time: updatedTime
    updated_by: updatedBy
    version: version

password:
  exp1: '.{8,}'
  exp2: '([a-z]){1,}'
  exp3: '([A-Z]){1,}'
  exp4: '([\d]){1,}'
  change_expires: 420
  reset_expires: 420
  schema:
    user_id: userId
    username: username
    to_address: email
    password: password
    changed_time: passwordModifiedTime
    fail_count: failCount
    changed_by: changedBy
    timestamp: timestamp
    history: history
  template:
    reset:
      subject: Passcode to reset password
      body: |
        Your user name is '%s'. This is the passcode to reset your password: %s. This passcode will expire in %s minutes.
        Tên đăng nhập của bạn là '%s'. Hãy dùng mã sau để tạo mật khẩu lại: %s. Mã này sẽ hết hạn trong %s phút.
    change:
      subject: Passcode to change password
      body: |
        Your user name is '%s'. This is the passcode to reset your password: %s. This passcode will expire in %s minutes.
        Tên đăng nhập của bạn là '%s'. Hãy dùng mã sau để thay đổi mật khẩu: %s. Mã này sẽ hết hạn trong %s phút.
